version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
    volumes:
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    networks:
      - sellscale-network

  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - sellscale-network

  frontend:
    build:
      context: ./frontend/scalehoodUI
    ports:
      - "5173:5173"
    networks:
      - sellscale-network

volumes:
  mysql_data:

networks:
  sellscale-network:

